---
Description: backup plan template to back up all resources daily.
Parameters:
  VaultName: 
    Type: String
    Default: 'vault-tags'
    Description: Name of the AWS Backup Vault where the backups will be stored.
  BackupPlanName:
    Type: String
    Default: 'tags-backup-resources'
    Description: Backup Plan name.
  SelectionName:
    Type: String
    Default: 'backup-tags'
    Description: Backup Rule name. 
  AliasName:
    Type: String
    Default: 'backup-tags'
    Description: Alias KMS Key
  ScheduleExpression:
    Type: String
    Default: "cron(0 23 ? * * *)"
    Description: A CRON expression specifying when AWS Backup initiates a backup job.
  TimeZone:
    Type: String
    Default: "America/Sao_Paulo"
    Description: Time Zone the rule will run.
  Retention:
    Type: String
    Default: "30"
    Description: AWS Backup automatically expires backups according to the lifecycle defined in the origin account.
  StartWindowMinutes:
    Type: String
    Default: "480"
    Description: That specifies a period of time in minutes after a backup is scheduled before a job is canceled if it doesn't start successfully.
  CompletionWindowMinutes:
    Type: String
    Default: "10080"
    Description: A value in minutes after a backup job is successfully started before it must be completed or it is canceled by AWS Backup.
  TagConditionType:
    Type: String
    Default: "STRINGEQUALS"
    Description: A conditions that you define to assign resources to your backup plans using tags. Conditions supports StringEquals, StringLike, StringNotEquals, and StringNotLike. ListOfTags only supports StringEquals.
  TagKey:
    Type: String
    Default: "TagKey"
    Description: Define Tag Key
  TagValue:
    Type: String
    Default: "TagValue"
    Description: Define Tag Value

Resources:
  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "Encryption key for daily"
      EnableKeyRotation: True
      Enabled: True
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              "AWS": { "Fn::Sub": "arn:${AWS::Partition}:iam::${AWS::AccountId}:root" }
            Action:
              - kms:*
            Resource: "*"
  KMSAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Ref AliasName
      TargetKeyId: !Ref KMSKey

  BackupVaultWithDailyBackups:
    DependsOn: KMSKey
    Type: AWS::Backup::BackupVault
    Properties:
      BackupVaultName: !Ref VaultName
      EncryptionKeyArn: !GetAtt KMSKey.Arn

  BackupPlanWithDailyBackups:
    DependsOn: BackupVaultWithDailyBackups
    Type: AWS::Backup::BackupPlan
    Properties:
      BackupPlan:
        BackupPlanName: !Ref BackupPlanName
        BackupPlanRule:
          -
            RuleName: "daily-backup-resources"
            TargetBackupVault: !Ref BackupVaultWithDailyBackups
            ScheduleExpression: !Ref ScheduleExpression
            ScheduleExpressionTimezone: !Ref TimeZone
            StartWindowMinutes: !Ref StartWindowMinutes
            CompletionWindowMinutes: !Ref CompletionWindowMinutes
            Lifecycle:
                DeleteAfterDays:  !Ref Retention
  
  BackupRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "backup.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup"
        - "arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForRestores"

  TagBasedBackupSelection:
    DependsOn: BackupPlanWithDailyBackups
    Type: AWS::Backup::BackupSelection
    Properties:
      BackupSelection:
        SelectionName: !Ref SelectionName
        IamRoleArn: !GetAtt BackupRole.Arn
        Resources:
          - "arn:aws:dynamodb:*:*:table/*"
          - "arn:aws:rds:*:*:cluster:*"
          - "arn:aws:rds:*:*:db:*"
        ListOfTags:
          - ConditionType: !Ref TagConditionType
            ConditionKey: !Ref TagKey
            ConditionValue: !Ref TagValue
      BackupPlanId: !Ref BackupPlanWithDailyBackups